// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/edgekv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	// A client command for the state machine.
	EntryType_ENTRY_NORMAL EntryType = 0
	// Appended by a new leader so that it can commit an entry from its own term
	// (Raft §5.4.2 / §8). Never reaches the state machine.
	EntryType_ENTRY_NOOP EntryType = 1
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_NORMAL",
		1: "ENTRY_NOOP",
	}
	EntryType_value = map[string]int32{
		"ENTRY_NORMAL": 0,
		"ENTRY_NOOP":   1,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_edgekv_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_proto_edgekv_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{0}
}

type Op int32

const (
	Op_OP_PUT    Op = 0
	Op_OP_DELETE Op = 1
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_PUT",
		1: "OP_DELETE",
	}
	Op_value = map[string]int32{
		"OP_PUT":    0,
		"OP_DELETE": 1,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_edgekv_proto_enumTypes[1].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_proto_edgekv_proto_enumTypes[1]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_STATUS_OK               Status = 0
	Status_STATUS_NOT_FOUND        Status = 1
	Status_STATUS_VERSION_MISMATCH Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_NOT_FOUND",
		2: "STATUS_VERSION_MISMATCH",
	}
	Status_value = map[string]int32{
		"STATUS_OK":               0,
		"STATUS_NOT_FOUND":        1,
		"STATUS_VERSION_MISMATCH": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_edgekv_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_edgekv_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{2}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=edgekv.v1.EntryType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_edgekv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_NORMAL
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// HardState is what Raft must make durable before answering any RPC.
type HardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VotedFor      string                 `protobuf:"bytes,2,opt,name=voted_for,json=votedFor,proto3" json:"voted_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardState) Reset() {
	*x = HardState{}
	mi := &file_proto_edgekv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardState) ProtoMessage() {}

func (x *HardState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardState.ProtoReflect.Descriptor instead.
func (*HardState) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{1}
}

func (x *HardState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HardState) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

type SnapshotMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex uint64                 `protobuf:"varint,1,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,2,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	// WAL segments with a sequence number below this must be ignored on
	// recovery. Set when a follower installs a snapshot that does not match its
	// log and therefore discards the whole log: writing it inside the snapshot
	// file makes "new snapshot + log reset" a single atomic rename.
	MinWalSegment uint64 `protobuf:"varint,3,opt,name=min_wal_segment,json=minWalSegment,proto3" json:"min_wal_segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMeta) Reset() {
	*x = SnapshotMeta{}
	mi := &file_proto_edgekv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMeta) ProtoMessage() {}

func (x *SnapshotMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMeta.ProtoReflect.Descriptor instead.
func (*SnapshotMeta) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotMeta) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *SnapshotMeta) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *SnapshotMeta) GetMinWalSegment() uint64 {
	if x != nil {
		return x.MinWalSegment
	}
	return 0
}

type RequestVoteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Group        uint32                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Term         uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId  string                 `protobuf:"bytes,3,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex uint64                 `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm  uint64                 `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	// Pre-vote (Raft thesis §9.6): ask "would you vote for me?" without
	// incrementing any term, so a partitioned node cannot disrupt a healthy
	// leader when it rejoins.
	PreVote       bool `protobuf:"varint,6,opt,name=pre_vote,json=preVote,proto3" json:"pre_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_proto_edgekv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteRequest) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RequestVoteRequest) GetPreVote() bool {
	if x != nil {
		return x.PreVote
	}
	return false
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_proto_edgekv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint32                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,4,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,7,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_proto_edgekv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEntriesRequest) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Term    uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Fast log backtracking (Raft §5.3, end): on a mismatch the follower tells
	// the leader which term conflicted and where that term starts, so the leader
	// skips a whole term per round trip instead of one entry.
	ConflictIndex uint64 `protobuf:"varint,3,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	ConflictTerm  uint64 `protobuf:"varint,4,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_proto_edgekv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{6}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *AppendEntriesResponse) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

type InstallSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Group             uint32                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Term              uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastIncludedIndex uint64                 `protobuf:"varint,4,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,5,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Data              []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_proto_edgekv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSnapshotRequest) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *InstallSnapshotRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *InstallSnapshotRequest) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_proto_edgekv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{8}
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

// InstallSnapshotChunk is the wire form of InstallSnapshotRequest: the first
// chunk carries the header (with empty data), later chunks only carry data.
type InstallSnapshotChunk struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Header        *InstallSnapshotRequest `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotChunk) Reset() {
	*x = InstallSnapshotChunk{}
	mi := &file_proto_edgekv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotChunk) ProtoMessage() {}

func (x *InstallSnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotChunk.ProtoReflect.Descriptor instead.
func (*InstallSnapshotChunk) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{9}
}

func (x *InstallSnapshotChunk) GetHeader() *InstallSnapshotRequest {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InstallSnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TimeoutNow tells the target to start an election immediately. It is the last
// step of a leadership transfer (Raft thesis §3.10).
type TimeoutNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint32                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowRequest) Reset() {
	*x = TimeoutNowRequest{}
	mi := &file_proto_edgekv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowRequest) ProtoMessage() {}

func (x *TimeoutNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowRequest.ProtoReflect.Descriptor instead.
func (*TimeoutNowRequest) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{10}
}

func (x *TimeoutNowRequest) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *TimeoutNowRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *TimeoutNowRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type TimeoutNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowResponse) Reset() {
	*x = TimeoutNowResponse{}
	mi := &file_proto_edgekv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowResponse) ProtoMessage() {}

func (x *TimeoutNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowResponse.ProtoReflect.Descriptor instead.
func (*TimeoutNowResponse) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{11}
}

func (x *TimeoutNowResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=edgekv.v1.Op" json:"op,omitempty"`
	Key   string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Compare-and-set: apply only if the key's current version equals
	// expected_version. 0 means "the key must not exist".
	HasExpectedVersion bool   `protobuf:"varint,4,opt,name=has_expected_version,json=hasExpectedVersion,proto3" json:"has_expected_version,omitempty"`
	ExpectedVersion    uint64 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	// Idempotency key. A retried command with the same request_id is not
	// executed again; the original result is returned.
	RequestId  string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Cacheable  bool   `protobuf:"varint,7,opt,name=cacheable,proto3" json:"cacheable,omitempty"`
	TtlSeconds uint32 `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Stamped by the leader when it proposes the command. The state machine
	// must be deterministic, so it may never read the clock itself.
	TimestampUnixMs int64 `protobuf:"varint,9,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_edgekv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{12}
}

func (x *Command) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_PUT
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Command) GetHasExpectedVersion() bool {
	if x != nil {
		return x.HasExpectedVersion
	}
	return false
}

func (x *Command) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Command) GetCacheable() bool {
	if x != nil {
		return x.Cacheable
	}
	return false
}

func (x *Command) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Command) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=edgekv.v1.Status" json:"status,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_edgekv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{13}
}

func (x *Result) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_OK
}

func (x *Result) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SnapshotRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Cacheable     bool                   `protobuf:"varint,5,opt,name=cacheable,proto3" json:"cacheable,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	UpdatedUnixMs int64                  `protobuf:"varint,7,opt,name=updated_unix_ms,json=updatedUnixMs,proto3" json:"updated_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRecord) Reset() {
	*x = SnapshotRecord{}
	mi := &file_proto_edgekv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecord) ProtoMessage() {}

func (x *SnapshotRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecord.ProtoReflect.Descriptor instead.
func (*SnapshotRecord) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SnapshotRecord) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotRecord) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SnapshotRecord) GetCacheable() bool {
	if x != nil {
		return x.Cacheable
	}
	return false
}

func (x *SnapshotRecord) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SnapshotRecord) GetUpdatedUnixMs() int64 {
	if x != nil {
		return x.UpdatedUnixMs
	}
	return 0
}

type SnapshotDedup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDedup) Reset() {
	*x = SnapshotDedup{}
	mi := &file_proto_edgekv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDedup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDedup) ProtoMessage() {}

func (x *SnapshotDedup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDedup.ProtoReflect.Descriptor instead.
func (*SnapshotDedup) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotDedup) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SnapshotDedup) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotDedup) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type StoreSnapshot struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*SnapshotRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// The deduplication table is part of the state machine. If it were left out
	// of the snapshot, a retry arriving after a restart would execute twice.
	Dedup         []*SnapshotDedup `protobuf:"bytes,2,rep,name=dedup,proto3" json:"dedup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSnapshot) Reset() {
	*x = StoreSnapshot{}
	mi := &file_proto_edgekv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSnapshot) ProtoMessage() {}

func (x *StoreSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgekv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSnapshot.ProtoReflect.Descriptor instead.
func (*StoreSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_edgekv_proto_rawDescGZIP(), []int{16}
}

func (x *StoreSnapshot) GetRecords() []*SnapshotRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *StoreSnapshot) GetDedup() []*SnapshotDedup {
	if x != nil {
		return x.Dedup
	}
	return nil
}

var File_proto_edgekv_proto protoreflect.FileDescriptor

const file_proto_edgekv_proto_rawDesc = "" +
	"\n" +
	"\x12proto/edgekv.proto\x12\tedgekv.v1\"o\n" +
	"\x05Entry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.edgekv.v1.EntryTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"<\n" +
	"\tHardState\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tvoted_for\x18\x02 \x01(\tR\bvotedFor\"\x94\x01\n" +
	"\fSnapshotMeta\x12.\n" +
	"\x13last_included_index\x18\x01 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x02 \x01(\x04R\x10lastIncludedTerm\x12&\n" +
	"\x0fmin_wal_segment\x18\x03 \x01(\x04R\rminWalSegment\"\xc6\x01\n" +
	"\x12RequestVoteRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\rR\x05group\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x03 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x04 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x05 \x01(\x04R\vlastLogTerm\x12\x19\n" +
	"\bpre_vote\x18\x06 \x01(\bR\apreVote\"L\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xf8\x01\n" +
	"\x14AppendEntriesRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\rR\x05group\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x04 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x05 \x01(\x04R\vprevLogTerm\x12*\n" +
	"\aentries\x18\x06 \x03(\v2\x10.edgekv.v1.EntryR\aentries\x12#\n" +
	"\rleader_commit\x18\a \x01(\x04R\fleaderCommit\"\x91\x01\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0econflict_index\x18\x03 \x01(\x04R\rconflictIndex\x12#\n" +
	"\rconflict_term\x18\x04 \x01(\x04R\fconflictTerm\"\xd1\x01\n" +
	"\x16InstallSnapshotRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\rR\x05group\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12.\n" +
	"\x13last_included_index\x18\x04 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x05 \x01(\x04R\x10lastIncludedTerm\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"-\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\"e\n" +
	"\x14InstallSnapshotChunk\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.edgekv.v1.InstallSnapshotRequestR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"Z\n" +
	"\x11TimeoutNowRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\rR\x05group\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\"(\n" +
	"\x12TimeoutNowResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\"\xb7\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\x02op\x18\x01 \x01(\x0e2\r.edgekv.v1.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x120\n" +
	"\x14has_expected_version\x18\x04 \x01(\bR\x12hasExpectedVersion\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x04R\x0fexpectedVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x1c\n" +
	"\tcacheable\x18\a \x01(\bR\tcacheable\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\rR\n" +
	"ttlSeconds\x12*\n" +
	"\x11timestamp_unix_ms\x18\t \x01(\x03R\x0ftimestampUnixMs\"M\n" +
	"\x06Result\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.edgekv.v1.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xd3\x01\n" +
	"\x0eSnapshotRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x1c\n" +
	"\tcacheable\x18\x05 \x01(\bR\tcacheable\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\rR\n" +
	"ttlSeconds\x12&\n" +
	"\x0fupdated_unix_ms\x18\a \x01(\x03R\rupdatedUnixMs\"o\n" +
	"\rSnapshotDedup\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.edgekv.v1.ResultR\x06result\"t\n" +
	"\rStoreSnapshot\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.edgekv.v1.SnapshotRecordR\arecords\x12.\n" +
	"\x05dedup\x18\x02 \x03(\v2\x18.edgekv.v1.SnapshotDedupR\x05dedup*-\n" +
	"\tEntryType\x12\x10\n" +
	"\fENTRY_NORMAL\x10\x00\x12\x0e\n" +
	"\n" +
	"ENTRY_NOOP\x10\x01*\x1f\n" +
	"\x02Op\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x00\x12\r\n" +
	"\tOP_DELETE\x10\x01*J\n" +
	"\x06Status\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x14\n" +
	"\x10STATUS_NOT_FOUND\x10\x01\x12\x1b\n" +
	"\x17STATUS_VERSION_MISMATCH\x10\x022\xcd\x02\n" +
	"\x04Raft\x12L\n" +
	"\vRequestVote\x12\x1d.edgekv.v1.RequestVoteRequest\x1a\x1e.edgekv.v1.RequestVoteResponse\x12R\n" +
	"\rAppendEntries\x12\x1f.edgekv.v1.AppendEntriesRequest\x1a .edgekv.v1.AppendEntriesResponse\x12X\n" +
	"\x0fInstallSnapshot\x12\x1f.edgekv.v1.InstallSnapshotChunk\x1a\".edgekv.v1.InstallSnapshotResponse(\x01\x12I\n" +
	"\n" +
	"TimeoutNow\x12\x1c.edgekv.v1.TimeoutNowRequest\x1a\x1d.edgekv.v1.TimeoutNowResponseB,Z*github.com/Tr3nt-Xie/EdgeKV/internal/pb;pbb\x06proto3"

var (
	file_proto_edgekv_proto_rawDescOnce sync.Once
	file_proto_edgekv_proto_rawDescData []byte
)

func file_proto_edgekv_proto_rawDescGZIP() []byte {
	file_proto_edgekv_proto_rawDescOnce.Do(func() {
		file_proto_edgekv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_edgekv_proto_rawDesc), len(file_proto_edgekv_proto_rawDesc)))
	})
	return file_proto_edgekv_proto_rawDescData
}

var file_proto_edgekv_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_edgekv_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_edgekv_proto_goTypes = []any{
	(EntryType)(0),                  // 0: edgekv.v1.EntryType
	(Op)(0),                         // 1: edgekv.v1.Op
	(Status)(0),                     // 2: edgekv.v1.Status
	(*Entry)(nil),                   // 3: edgekv.v1.Entry
	(*HardState)(nil),               // 4: edgekv.v1.HardState
	(*SnapshotMeta)(nil),            // 5: edgekv.v1.SnapshotMeta
	(*RequestVoteRequest)(nil),      // 6: edgekv.v1.RequestVoteRequest
	(*RequestVoteResponse)(nil),     // 7: edgekv.v1.RequestVoteResponse
	(*AppendEntriesRequest)(nil),    // 8: edgekv.v1.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),   // 9: edgekv.v1.AppendEntriesResponse
	(*InstallSnapshotRequest)(nil),  // 10: edgekv.v1.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 11: edgekv.v1.InstallSnapshotResponse
	(*InstallSnapshotChunk)(nil),    // 12: edgekv.v1.InstallSnapshotChunk
	(*TimeoutNowRequest)(nil),       // 13: edgekv.v1.TimeoutNowRequest
	(*TimeoutNowResponse)(nil),      // 14: edgekv.v1.TimeoutNowResponse
	(*Command)(nil),                 // 15: edgekv.v1.Command
	(*Result)(nil),                  // 16: edgekv.v1.Result
	(*SnapshotRecord)(nil),          // 17: edgekv.v1.SnapshotRecord
	(*SnapshotDedup)(nil),           // 18: edgekv.v1.SnapshotDedup
	(*StoreSnapshot)(nil),           // 19: edgekv.v1.StoreSnapshot
}
var file_proto_edgekv_proto_depIdxs = []int32{
	0,  // 0: edgekv.v1.Entry.type:type_name -> edgekv.v1.EntryType
	3,  // 1: edgekv.v1.AppendEntriesRequest.entries:type_name -> edgekv.v1.Entry
	10, // 2: edgekv.v1.InstallSnapshotChunk.header:type_name -> edgekv.v1.InstallSnapshotRequest
	1,  // 3: edgekv.v1.Command.op:type_name -> edgekv.v1.Op
	2,  // 4: edgekv.v1.Result.status:type_name -> edgekv.v1.Status
	16, // 5: edgekv.v1.SnapshotDedup.result:type_name -> edgekv.v1.Result
	17, // 6: edgekv.v1.StoreSnapshot.records:type_name -> edgekv.v1.SnapshotRecord
	18, // 7: edgekv.v1.StoreSnapshot.dedup:type_name -> edgekv.v1.SnapshotDedup
	6,  // 8: edgekv.v1.Raft.RequestVote:input_type -> edgekv.v1.RequestVoteRequest
	8,  // 9: edgekv.v1.Raft.AppendEntries:input_type -> edgekv.v1.AppendEntriesRequest
	12, // 10: edgekv.v1.Raft.InstallSnapshot:input_type -> edgekv.v1.InstallSnapshotChunk
	13, // 11: edgekv.v1.Raft.TimeoutNow:input_type -> edgekv.v1.TimeoutNowRequest
	7,  // 12: edgekv.v1.Raft.RequestVote:output_type -> edgekv.v1.RequestVoteResponse
	9,  // 13: edgekv.v1.Raft.AppendEntries:output_type -> edgekv.v1.AppendEntriesResponse
	11, // 14: edgekv.v1.Raft.InstallSnapshot:output_type -> edgekv.v1.InstallSnapshotResponse
	14, // 15: edgekv.v1.Raft.TimeoutNow:output_type -> edgekv.v1.TimeoutNowResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_edgekv_proto_init() }
func file_proto_edgekv_proto_init() {
	if File_proto_edgekv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_edgekv_proto_rawDesc), len(file_proto_edgekv_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_edgekv_proto_goTypes,
		DependencyIndexes: file_proto_edgekv_proto_depIdxs,
		EnumInfos:         file_proto_edgekv_proto_enumTypes,
		MessageInfos:      file_proto_edgekv_proto_msgTypes,
	}.Build()
	File_proto_edgekv_proto = out.File
	file_proto_edgekv_proto_goTypes = nil
	file_proto_edgekv_proto_depIdxs = nil
}
